# Generated by Django 5.2.15 on 2026-06-17 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="specialty",
            field=models.CharField(
                blank=True,
                choices=[
                    ("FULL_STACK", "Full Stack Software Engineering"),
                    ("MOBILE_DEV", "Mobile App Development"),
                    ("CYBER_SECURITY", "Cyber Security"),
                    ("DATA_ANALYSIS", "Data Analysis"),
                    ("MACHINE_LEARNING", "Machine Learning"),
                    ("RESEARCH", "Research Work"),
                    ("CREATIVE_AI", "Creative Tech (AI)"),
                    ("VIRTUAL_ASSISTANCE", "Virtual Assistance"),
                    ("CONTENT_CREATION", "Content Creation"),
                    ("LAB_DIAGNOSTICS", "Laboratory Diagnostics"),
                    ("USG_SCANNING", "USG / Ultrasound Scanning"),
                    ("DNA_TESTING", "DNA Testing"),
                    ("HEALTH_ADVISORY", "Health Advisory & Consulting"),
                    ("TELEHEALTH", "Telehealth Support"),
                    ("PROGRAMS_HEALTH", "Health Programs"),
                    ("PROGRAMS_EDUCATION", "Education Programs"),
                    ("PROGRAMS_YOUTH", "Youth Empowerment Programs"),
                    ("VOLUNTEER_COORD", "Volunteer Coordination"),
                    ("EXEC_ASSISTANCE", "Executive Assistance"),
                    ("BUSINESS_OPS", "Business Operations"),
                    ("CRM_MANAGEMENT", "CRM Management"),
                ],
                help_text="Professional specialty — relevant for TECH, MEDICAL, FOUNDATION, and VA roles.",
                max_length=30,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Admin"),
                    ("MEDICAL", "Medical Services"),
                    ("TECH", "Tech Specialist"),
                    ("VA", "Virtual Assistant"),
                    ("CLIENT", "Client"),
                    ("FOUNDATION", "Foundation"),
                ],
                default="CLIENT",
                max_length=20,
            ),
        ),
    ]
