# Generated by Django 5.2.15 on 2026-10-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_is_available_for_calls"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_notifications",
            field=models.BooleanField(
                default=True,
                help_text="Staff toggle — also send dashboard notifications to this user's email address.",
            ),
        ),
    ]
