# Generated by Django 5.2.15 on 2026-10-07 04:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PortalApp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(unique=True)),
                (
                    "tagline",
                    models.CharField(
                        help_text="One line shown on the card.", max_length=140
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "url",
                    models.CharField(
                        help_text="Full address, e.g. https://farmasyst.wolbiroyal.com",
                        max_length=300,
                        validators=[
                            django.core.validators.URLValidator(
                                schemes=["http", "https"]
                            )
                        ],
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g. Health, Agriculture, Finance",
                        max_length=40,
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, help_text="One emoji, e.g. 🌾", max_length=8
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#1e3a5f",
                        help_text="Accent colour, e.g. #16a34a",
                        max_length=7,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("LIVE", "Live"),
                            ("BETA", "Beta"),
                            ("COMING_SOON", "Coming soon"),
                        ],
                        default="LIVE",
                        max_length=12,
                    ),
                ),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("PUBLIC", "Public — shown on the public Apps page"),
                            (
                                "MEMBERS",
                                "Members — only after signing in to the dashboard",
                            ),
                        ],
                        default="PUBLIC",
                        max_length=10,
                    ),
                ),
                (
                    "allowed_roles",
                    models.CharField(
                        blank=True,
                        help_text="Members apps only. Comma-separated roles that can see it (ADMIN, MEDICAL, TECH, VA, CLIENT, FOUNDATION). Leave blank for every signed-in user. Admins always see everything.",
                        max_length=120,
                    ),
                ),
                ("open_in_new_tab", models.BooleanField(default=True)),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=100, help_text="Lower numbers appear first."
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Untick to hide without deleting."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "app",
                "ordering": ["order", "name"],
            },
        ),
    ]
