# Generated by Django 5.2.15 on 2026-10-08 00:35

import portal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="portalapp",
            name="icon_image",
            field=models.ImageField(
                blank=True,
                help_text="Upload the app's logo (square PNG, JPG or WebP, under 2 MB works best). Shown instead of the emoji below.",
                null=True,
                upload_to="portal/icons/",
                validators=[portal.models.validate_icon_size],
            ),
        ),
        migrations.AlterField(
            model_name="portalapp",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Fallback emoji if no logo is uploaded, e.g. 🌾",
                max_length=8,
            ),
        ),
    ]
