# Generated by Django 5.2.15 on 2026-10-07 03:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("to", models.CharField(max_length=500)),
                ("subject", models.CharField(max_length=300)),
                (
                    "audience",
                    models.CharField(
                        choices=[("CLIENT", "Client"), ("STAFF", "Staff")],
                        max_length=10,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        help_text="Which event sent it, e.g. lead_confirmation",
                        max_length=40,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "Queued"),
                            ("SENT", "Sent"),
                            ("FAILED", "Failed"),
                        ],
                        default="QUEUED",
                        max_length=10,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                (
                    "provider_id",
                    models.CharField(
                        blank=True, help_text="Resend message id", max_length=100
                    ),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("text_body", models.TextField(blank=True)),
                ("html_body", models.TextField(blank=True)),
                ("reply_to", models.CharField(blank=True, max_length=300)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="kind",
            field=models.CharField(
                choices=[
                    ("LEAD", "New request"),
                    ("LEAD_ESCALATION", "AI concierge hand-off"),
                    ("TELECONSULTATION", "Teleconsultation"),
                    ("VOLUNTEER", "Volunteer application"),
                    ("ASSIGNMENT", "Assignment"),
                    ("COMMENT", "Comment"),
                    ("SYSTEM", "System"),
                ],
                default="SYSTEM",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="link",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(
                fields=["user", "is_read"], name="notificatio_user_id_427e4b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="emaillog",
            index=models.Index(
                fields=["status", "created_at"], name="notificatio_status_6192b4_idx"
            ),
        ),
    ]
