# Generated by Django 5.2.15 on 2026-10-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_emaillog_notification_kind_notification_link_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="emaillog",
            name="from_email",
            field=models.CharField(
                blank=True,
                help_text="Sender shown to the recipient; blank means the default sender",
                max_length=300,
            ),
        ),
    ]
