# Generated by Django 6.0.6 on 2026-06-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "business_unit",
                    models.CharField(
                        choices=[
                            ("TECHNOLOGIES", "Wolbi Technologies"),
                            ("MEDICAL", "Wolbi Medical Services"),
                            ("FOUNDATION", "Wolbi Foundation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("summary", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNING", "Planning"),
                            ("ACTIVE", "Active"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PLANNING",
                        max_length=20,
                    ),
                ),
                ("featured", models.BooleanField(default=False)),
                ("project_url", models.URLField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
