# Generated by Django 6.0.6 on 2026-06-08 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("PRODUCT", "Product"),
                    ("CASE_STUDY", "Case Study"),
                    ("INTERNAL", "Internal Project"),
                ],
                default="CASE_STUDY",
                max_length=20,
            ),
        ),
    ]
