# Generated by Django 6.0.6 on 2026-06-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                (
                    "business_unit",
                    models.CharField(
                        choices=[
                            ("TECHNOLOGIES", "Wolbi Technologies"),
                            ("MEDICAL", "Wolbi Medical Services"),
                            ("FOUNDATION", "Wolbi Foundation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("short_description", models.CharField(max_length=300)),
                ("description", models.TextField()),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
            ],
        ),
    ]
