# Generated by Django 6.0.6 on 2026-06-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_service_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"ordering": ["business_unit", "name"]},
        ),
        migrations.AlterField(
            model_name="service",
            name="business_unit",
            field=models.CharField(
                choices=[
                    ("TECHNOLOGIES", "Wolbi Technologies"),
                    ("MEDICAL", "Wolbi Medical Services"),
                    ("VIRTUAL_SOLUTIONS", "Wolbi Virtual Solutions"),
                    ("FOUNDATION", "Wolbi Foundation"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
