# Generated by Django 5.2.15 on 2026-10-07 03:06

import teleconsultations.models
import secrets

from django.db import migrations, models


def give_each_session_its_own_token(apps, schema_editor):
    # AddField fills existing rows with ONE shared default value; replace it
    # with a unique token per session.
    Session = apps.get_model("teleconsultations", "ConsultationSession")
    for session in Session.objects.all().only("pk"):
        Session.objects.filter(pk=session.pk).update(access_token=secrets.token_urlsafe(24))


class Migration(migrations.Migration):

    dependencies = [
        ("teleconsultations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationsession",
            name="access_token",
            field=models.CharField(
                default=teleconsultations.models._new_access_token,
                editable=False,
                max_length=64,
            ),
        ),
        migrations.RunPython(give_each_session_its_own_token, migrations.RunPython.noop),
    ]
