# Generated by Django 5.2.15 on 2026-10-08 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("teleconsultations", "0002_consultationsession_access_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="consultationsession",
            name="cancelled_by",
            field=models.CharField(
                blank=True, help_text="client, staff or system", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="consultationsession",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationsession",
            name="duration_minutes",
            field=models.PositiveSmallIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="consultationsession",
            name="ended_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationsession",
            name="reminder_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationsession",
            name="room_expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="consultationsession",
            name="started_at",
            field=models.DateTimeField(
                blank=True, help_text="When the first person joined", null=True
            ),
        ),
        migrations.AddField(
            model_name="consultationsession",
            name="timezone",
            field=models.CharField(
                blank=True,
                help_text="Client's IANA timezone (e.g. Europe/London) so emails show their local time",
                max_length=64,
            ),
        ),
        migrations.AlterField(
            model_name="consultationsession",
            name="status",
            field=models.CharField(
                choices=[
                    ("REQUESTED", "Requested"),
                    ("CONFIRMED", "Confirmed"),
                    ("CLAIMED", "In progress"),
                    ("COMPLETED", "Completed"),
                    ("CANCELLED", "Cancelled"),
                    ("MISSED", "Missed"),
                ],
                default="REQUESTED",
                max_length=10,
            ),
        ),
    ]
