# Generated by Django 6.0.6 on 2026-06-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Industry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("icon", models.CharField(blank=True, max_length=100)),
                ("short_description", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "challenges",
                    models.TextField(
                        blank=True, help_text="Key challenges in this industry"
                    ),
                ),
                (
                    "wolbi_solutions",
                    models.TextField(
                        blank=True, help_text="How Wolbi addresses these challenges"
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="industries/"),
                ),
                ("featured", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Industries",
                "ordering": ["sort_order", "name"],
            },
        ),
    ]
