# Generated by Django 6.0.6 on 2026-06-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=200)),
                ("author_title", models.CharField(blank=True, max_length=200)),
                ("author_company", models.CharField(blank=True, max_length=200)),
                (
                    "author_image",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("quote", models.TextField()),
                (
                    "division",
                    models.CharField(
                        choices=[
                            ("TECHNOLOGIES", "Wolbi Technologies"),
                            ("MEDICAL", "Wolbi Medical Services"),
                            ("VIRTUAL_SOLUTIONS", "Wolbi Virtual Solutions"),
                            ("FOUNDATION", "Wolbi Foundation"),
                            ("GENERAL", "General"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("rating", models.PositiveSmallIntegerField(default=5)),
                ("featured", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-featured", "-created_at"],
            },
        ),
    ]
