# Generated by Django 6.0.6 on 2026-06-13 00:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assignments", "0001_initial"),
        ("leads", "0003_alter_lead_options_lead_notes_lead_organization_and_more"),
        ("projects", "0004_alter_project_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="assignmentcomment",
            options={"ordering": ["created_at"]},
        ),
        migrations.AlterField(
            model_name="assignment",
            name="lead",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="leads.lead",
            ),
        ),
        migrations.AlterField(
            model_name="assignment",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assignments",
                to="projects.project",
            ),
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
