# Generated by Django 6.0.6 on 2026-06-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=30)),
                (
                    "inquiry_type",
                    models.CharField(
                        choices=[
                            ("MEDICAL", "Medical Services"),
                            ("TECHNOLOGY", "Technology"),
                            ("VA", "Virtual Assistant"),
                            ("AGRICULTURE", "Agriculture"),
                            ("HOSPITALITY", "Hospitality"),
                            ("REAL_ESTATE", "Real Estate"),
                            ("CONSTRUCTION", "Construction"),
                            ("FOUNDATION", "Foundation"),
                            ("GENERAL", "General Inquiry"),
                        ],
                        default="GENERAL",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_contacted", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
