# Generated by Django 6.0.6 on 2026-06-13 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_alter_lead_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lead",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="lead",
            name="notes",
            field=models.TextField(blank=True, help_text="Internal notes"),
        ),
        migrations.AddField(
            model_name="lead",
            name="organization",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="lead",
            name="product_interest",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="lead",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="inquiry_type",
            field=models.CharField(
                choices=[
                    ("GENERAL", "General Inquiry"),
                    ("TECHNOLOGY", "Wolbi Technologies"),
                    ("MEDICAL", "Wolbi Medical Services"),
                    ("VIRTUAL", "Wolbi Virtual Solutions"),
                    ("FOUNDATION", "Wolbi Foundation"),
                    ("AGRICULTURE", "FarmaSyst / Agriculture"),
                    ("PARTNERSHIP", "Partnership"),
                    ("DEMO", "Product Demo Request"),
                ],
                default="GENERAL",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="subject",
            field=models.CharField(max_length=300),
        ),
    ]
