# Generated by Django 6.0.6 on 2026-06-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=200)),
                ("hero_title", models.CharField(max_length=300)),
                ("hero_subtitle", models.TextField()),
                ("about_text", models.TextField()),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=30)),
                ("address", models.TextField(blank=True)),
                ("linkedin_url", models.URLField(blank=True)),
                ("facebook_url", models.URLField(blank=True)),
                ("x_url", models.URLField(blank=True)),
                ("instagram_url", models.URLField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Site Configuration",
                "verbose_name_plural": "Site Configuration",
            },
        ),
    ]
